version: '3.9'

services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init_database.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local