version: '3.9'

services:
  dev_app:
    container_name: dev_app
    image: qloots/dev_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://dev_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - dev_db

  dev_db:
    container_name: dev_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

volumes:
  pgdata: {}