spring:
    datasource:
        url: jdbc:postgresql://localhost:54320/postgres
        username: postgres
        password: postgres

    jpa:
        properties:
            hibernate:
                ddl-auto: update
                dialect: org.hibernate.dialect.PostgreSQLDialect